### ISSUE TITLE
Enhancment request: Adding pydentic/py class model decoder/encoder

### ISSUE THREAD

**Issue by grizzly-monkey** [nonchan7720/sqs-polling#26]
If possible do you think it would be a good idea to provide an alternative way to say give out response as a pydentic class as well ?

which can save extra effort of str -> json -> class as mostly people use json or class types

**Comment by nonchan7720** [comment]
The message body may be encrypted for use, and decoding it should be the responsibility of the application using it.

**Comment by grizzly-monkey** [comment]
may be they did not think of encrypted use-case of a message https://pypi.org/project/pydantic-sqs/
but looks more intuitive would be great if we can have this in this lib i am anyways going to use this library i like it . 👍🏼 😄  thanks for making it opensource.

**Comment by nonchan7720** [comment]
However, I understand what you are saying and will try to think of ways to make it work.

**Comment by grizzly-monkey** [comment]
should i keep the issue open ?

**Comment by nonchan7720** [comment]
Yes, I would like it to remain Open 🙏.
